/*---- Generated by CellsDesigner at 15.06.2007 ----*/

package org.nalizadeh.designer.examples;

import org.nalizadeh.designer.layouts.boxlayout.BoxLayout2;

import java.awt.Dimension;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 * <p>Title:</p>
 *
 * <p>Description:</p>
 *
 * <p>Copyright: Copyright (c) 2007</p>
 *
 * <p>Organisation:</p>
 *
 * @author   undefined
 * @version  1.0
 */

public class BoxLayoutTest extends JPanel {

	private BoxLayout2 layout = new BoxLayout2(this, BoxLayout2.X_AXIS);

	private JLabel label2 = new JLabel();
	private JScrollPane scrollpane0 = new JScrollPane();
	private JList scrollpane0_list0 = new JList();
	private JLabel label0 = new JLabel();
	private JTextField textfield0 = new JTextField();
	private JLabel label1 = new JLabel();
	private JComboBox combobox0 = new JComboBox();

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	public BoxLayoutTest() {
		doInit();
	}

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	private void doInit() {
		setLayout(layout);

		label0.setText("Text:");
                label1.setText("Hello:");
                label2.setText("Name:");
		scrollpane0.setPreferredSize(new Dimension(123, 255));
		scrollpane0.getViewport().add(scrollpane0_list0);
		textfield0.setText("JTextField");

		add(label2);
		add(scrollpane0);
		add(label0);
		add(textfield0);
		add(label1);
		add(combobox0);
	}

}
