/*---- Generated by The Cells at 06.10.2013 ----*/

package org.nalizadeh.designer.examples;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
* <p>Title:<p>
*
* <p>Description:<p>
*
* <p>Copyright: Copyright (c) 2007<p>
*
* <p>Organisation:<p>
*
* @author   undefined
* @version  1.0
*/

public class FileRenamerPanel extends JPanel {

     private BorderLayout layout = new BorderLayout(4, 4);

     private LayoutManager panel1_layout = null;

     private FlowLayout panel3_layout = new FlowLayout(FlowLayout.LEFT, 4, 4);

     private FlowLayout panel2_layout = new FlowLayout(FlowLayout.RIGHT, 4, 4);

     JPanel panel1 = new JPanel();
     JButton panel1_button1 = new JButton();
     JButton panel1_button2 = new JButton();
     JScrollPane panel1_scrollpane1 = new JScrollPane();
     JList panel1_scrollpane1_list1 = new JList();
     JButton panel1_button3 = new JButton();
     JTextField panel1_textfield1 = new JTextField();
     JLabel panel1_label1 = new JLabel();
     JTextField panel1_textfield2 = new JTextField();
     JButton panel1_button4 = new JButton();
     JProgressBar panel1_progressbar1 = new JProgressBar();
     JPanel panel3 = new JPanel();
     JLabel panel3_label2 = new JLabel();
     JPanel panel2 = new JPanel();
     JButton panel2_button5 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public FileRenamerPanel() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          panel1_button1.setText("add directory...");
          panel1_button2.setText("remove directory");
          panel1_scrollpane1.getViewport().add(panel1_scrollpane1_list1);
          panel1_button3.setText("target directory...");
          panel1_textfield1.setText("");
          panel1_label1.setFont(new Font("Tahoma", 0, 11));
          panel1_label1.setForeground(new Color(0, 0, 0));
          panel1_label1.setPreferredSize(new Dimension(32, 14));
          panel1_label1.setText("Prefix:");
          panel1_textfield2.setText("");
          panel1_button4.setText("START");
          panel3_label2.setFont(new Font("Tahoma Fett", 1, 25));
          panel3_label2.setText("JFileRenamer");
          panel2_button5.setText("Close");

          initPanel1();
          initPanel2();
          initPanel3();

          add(panel1, BorderLayout.CENTER);
          add(panel3, BorderLayout.NORTH);
          add(panel2, BorderLayout.SOUTH);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_button1);
          panel1_button1.setBounds(new Rectangle(14, 12, 127, 23));
          panel1.add(panel1_button2);
          panel1_button2.setBounds(new Rectangle(14, 39, 127, 23));
          panel1.add(panel1_scrollpane1);
          panel1_scrollpane1.setBounds(new Rectangle(167, 12, 263, 84));
          panel1.add(panel1_button3);
          panel1_button3.setBounds(new Rectangle(14, 104, 127, 23));
          panel1.add(panel1_textfield1);
          panel1_textfield1.setBounds(new Rectangle(167, 107, 263, 20));
          panel1.add(panel1_label1);
          panel1_label1.setBounds(new Rectangle(17, 134, 127, 20));
          panel1.add(panel1_textfield2);
          panel1_textfield2.setBounds(new Rectangle(167, 134, 138, 20));
          panel1.add(panel1_button4);
          panel1_button4.setBounds(new Rectangle(167, 162, 138, 23));
          panel1.add(panel1_progressbar1);
          panel1_progressbar1.setBounds(new Rectangle(167, 196, 263, 20));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel2() {
          panel2.setLayout(panel2_layout);
          panel2.add(panel2_button5);
          panel2_button5.setPreferredSize(new Dimension(73, 23));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel3() {
          panel3.setLayout(panel3_layout);
          panel3.add(panel3_label2);
          panel3_label2.setPreferredSize(new Dimension(234, 20));
     }

}

