/*---- Generated by CellsDesigner at 01.07.2007 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * <p>Title:
 *
 * <p>
 * <p>Description:
 *
 * <p>
 * <p>Copyright: Copyright (c) 2007
 *
 * <p>
 * <p>Organisation:
 *
 * <p>
 *
 * @author   undefined
 * @version  1.0
 */

public class FlowLayoutTest extends JPanel {

	private FlowLayout layout = new FlowLayout(FlowLayout.CENTER, 5, 5);

	private JSpinner spinner0 = new JSpinner();
	private JLabel label0 = new JLabel();
	private JTextField textfield0 = new JTextField();
	private JButton button0 = new JButton();
	private JScrollPane scrollpane0 = new JScrollPane();
	private JTextArea scrollpane0_Textarea0 = new JTextArea();
	private JComboBox combobox0 = new JComboBox();

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	public FlowLayoutTest() {
		doInit();
	}

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	private void doInit() {
		setLayout(layout);

		spinner0.setPreferredSize(new Dimension(65, 20));
		textfield0.setPreferredSize(new Dimension(121, 27));
		textfield0.setText("");
		button0.setPreferredSize(new Dimension(200, 51));
		button0.setMaximumSize(new Dimension(53, 23));
		button0.setText("help");
		label0.setText("hello world");
		button0.setMinimumSize(new Dimension(53, 23));
		scrollpane0.setPreferredSize(new Dimension(105, 22));
		scrollpane0.getViewport().add(scrollpane0_Textarea0);
		combobox0.setPreferredSize(new Dimension(64, 18));

		add(spinner0);
		add(label0);
		add(textfield0);
		add(button0);
		add(scrollpane0);
		add(combobox0);
	}

}
