/*---- Generated by CellsDesigner at 19.03.2008 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Color;
import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class FreeLayoutTest extends JPanel {

     private LayoutManager layout = null;

     private LayoutManager tabbedpane1_panel1_layout = null;

     private LayoutManager tabbedpane1_panel2_layout = null;

     private double[][] tabbedpane1_panel3_constraints = {
          {20.0, 20.0, CellsLayout.FILL, },
          {60.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout tabbedpane1_panel3_layout = new CellsLayout(tabbedpane1_panel3_constraints, 2, 2);

     private JLabel label3 = new JLabel();
     private JTabbedPane tabbedpane1 = new JTabbedPane();
     JPanel tabbedpane1_panel1 = new JPanel();
     JLabel tabbedpane1_panel1_label5 = new JLabel();
     JScrollPane tabbedpane1_panel1_scrollpane2 = new JScrollPane();
     JTable tabbedpane1_panel1_scrollpane2_table1 = new JTable();
     JPanel tabbedpane1_panel2 = new JPanel();
     JPanel tabbedpane1_panel3 = new JPanel();
     JLabel tabbedpane1_panel3_label6 = new JLabel();
     JTextField tabbedpane1_panel3_textfield3 = new JTextField();
     JLabel tabbedpane1_panel3_label7 = new JLabel();
     JScrollPane tabbedpane1_panel3_scrollpane3 = new JScrollPane();
     JList tabbedpane1_panel3_scrollpane3_list1 = new JList();
     private JLabel label2 = new JLabel();
     private JLabel label1 = new JLabel();
     private JLabel label0 = new JLabel();
     private JTextField textfield0 = new JTextField();
     private JComboBox combobox0 = new JComboBox();
     private JScrollPane scrollpane1 = new JScrollPane();
     private JTree scrollpane1_tree1 = new JTree();
     private JButton button1 = new JButton();
     JButton button2 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public FreeLayoutTest() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          setBackground(new Color(213, 213, 163));
          label3.setFont(new Font("Tahoma Fett", 1, 12));
          label3.setForeground(new Color(255, 102, 102));
          label3.setText("Components");
          tabbedpane1_panel1.setBackground(new Color(212, 208, 200));
          tabbedpane1_panel1_label5.setText("Names:");
          tabbedpane1_panel1_scrollpane2.getViewport().add(tabbedpane1_panel1_scrollpane2_table1);
          tabbedpane1_panel1_scrollpane2_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          tabbedpane1_panel3_label6.setText("JLabel:");
          tabbedpane1_panel3_textfield3.setText("JTextField");
          tabbedpane1_panel3_label7.setText("JLabel:");
          tabbedpane1_panel3_scrollpane3.getViewport().add(tabbedpane1_panel3_scrollpane3_list1);
          label2.setText("Name:");
          label1.setFont(new Font("Tahoma", 0, 11));
          label1.setText("Type:");
          label0.setText("Description:");
          textfield0.setText("JTextField");
          scrollpane1.getViewport().add(scrollpane1_tree1);
          button1.setText("Ok");
          button2.setText("Cancel");

          textfield0.addMouseListener(new textfield0_MouseListener());
          initTabbedpane1_panel1();
          initTabbedpane1_panel2();
          initTabbedpane1_panel3();

          add(label3);
          label3.setBounds(new Rectangle(18, 20, 96, 20));
          add(tabbedpane1);
          tabbedpane1.setBounds(new Rectangle(96, 134, 352, 144));
          add(label2);
          label2.setBounds(new Rectangle(19, 45, 63, 20));
          add(label1);
          label1.setBounds(new Rectangle(18, 68, 68, 20));
          add(label0);
          label0.setBounds(new Rectangle(18, 98, 74, 20));
          add(textfield0);
          textfield0.setBounds(new Rectangle(92, 43, 199, 22));
          add(combobox0);
          combobox0.setBounds(new Rectangle(92, 76, 200, 23));
          add(scrollpane1);
          scrollpane1.setBounds(new Rectangle(347, 20, 100, 100));
          add(button1);
          button1.setBounds(new Rectangle(380, 289, 68, 26));
          add(button2);
          button2.setBounds(new Rectangle(306, 289, 69, 26));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel1() {
          tabbedpane1_panel1.setLayout(tabbedpane1_panel1_layout);
          tabbedpane1_panel1.add(tabbedpane1_panel1_label5);
          tabbedpane1_panel1_label5.setBounds(new Rectangle(9, 8, 49, 20));
          tabbedpane1_panel1.add(tabbedpane1_panel1_scrollpane2);
          tabbedpane1_panel1_scrollpane2.setBounds(new Rectangle(9, 34, 330, 74));
          tabbedpane1.add("tab1", tabbedpane1_panel1);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel2() {
          tabbedpane1_panel2.setLayout(tabbedpane1_panel2_layout);
          tabbedpane1.add("tab2", tabbedpane1_panel2);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel3() {
          tabbedpane1_panel3.setLayout(tabbedpane1_panel3_layout);
          tabbedpane1_panel3.add(tabbedpane1_panel3_label6, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel3.add(tabbedpane1_panel3_textfield3, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel3.add(tabbedpane1_panel3_label7, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel3.add(tabbedpane1_panel3_scrollpane3, new CellsLayout.Cell(1, 1, false, 1, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1.add("views", tabbedpane1_panel3);
     }

    /**
     *
     *
     */
     private class textfield0_MouseListener implements MouseListener {

          public void mouseClicked(MouseEvent e) {
          }

          public void mouseEntered(MouseEvent e) {
          }

          public void mouseExited(MouseEvent e) {
          }

          public void mousePressed(MouseEvent e) {
          }

          public void mouseReleased(MouseEvent e) {
          }
     }

}

