/*---- Generated by CellsDesigner at 19.09.2007 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class GridBagLayoutTest extends JPanel {

     private GridBagLayout layout = new GridBagLayout();

     private FlowLayout panel1_layout = new FlowLayout(FlowLayout.RIGHT, 5, 0);

     private FlowLayout panel2_layout = new FlowLayout(FlowLayout.LEFT, 4, 0);

     private JLabel label0 = new JLabel();
     private JLabel label1 = new JLabel();
     private JTextField textfield0 = new JTextField();
     private JScrollPane scrollpane1 = new JScrollPane();
     private JTable scrollpane1_table1 = new JTable();
     private JPanel panel1 = new JPanel();
     private JButton panel1_button1 = new JButton();
     private JButton panel1_button2 = new JButton();
     private JPanel panel2 = new JPanel();
     private JRadioButton panel2_radiobutton1 = new JRadioButton();
     private JRadioButton panel2_radiobutton2 = new JRadioButton();
     private JRadioButton panel2_radiobutton3 = new JRadioButton();
     private JCheckBox checkbox0 = new JCheckBox();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public GridBagLayoutTest() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          label0.setText("Name:");
          label1.setText("Price:");
          textfield0.setText("");
          scrollpane1.getViewport().add(scrollpane1_table1);
          scrollpane1_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          panel1_button1.setPreferredSize(new Dimension(80, 23));
          panel1_button1.setText("Ok");
          panel1_button2.setPreferredSize(new Dimension(80, 23));
          panel1_button2.setText("Cancel");
          panel2_radiobutton1.setText("USD");
          panel2_radiobutton2.setText("Euro");
          panel2_radiobutton3.setText("Yen");
          checkbox0.setText("Currency");

          initPanel1();
          initPanel2();

          add(label0, new GridBagConstraints(0, 0, 1, 1, 0., 0.,
               GridBagConstraints.NORTHWEST, GridBagConstraints.NONE, new Insets(0, 0, 0, 0), 0, 0));
          add(label1, new GridBagConstraints(0, 1, 1, 1, 0., 0.,
               GridBagConstraints.NORTHWEST, GridBagConstraints.NONE, new Insets(5, 0, 0, 0), 0, 0));
          add(textfield0, new GridBagConstraints(1, 0, 1, 1, 0., 0.,
               GridBagConstraints.NORTHWEST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 62, 0));
          add(scrollpane1, new GridBagConstraints(1, 1, 1, 1, 1., 1.,
               GridBagConstraints.CENTER, GridBagConstraints.BOTH, new Insets(5, 0, 0, 0), 0, 0));
          add(panel1, new GridBagConstraints(1, 4, 1, 1, 0., 0.,
               GridBagConstraints.EAST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 5, 0), 0, 0));
          add(panel2, new GridBagConstraints(1, 3, 1, 1, 0., 0.,
               GridBagConstraints.NORTHWEST, GridBagConstraints.NONE, new Insets(0, 0, 0, 0), 0, 0));
          add(checkbox0, new GridBagConstraints(0, 3, 1, 1, 0., 0.,
               GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, 0));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_button1);
          panel1.add(panel1_button2);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel2() {
          panel2.setLayout(panel2_layout);
          panel2.add(panel2_radiobutton1);
          panel2.add(panel2_radiobutton2);
          panel2.add(panel2_radiobutton3);
     }

}

