/*---- Generated by CellsDesigner at 01.07.2007 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.GridLayout;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 * <p>Title:</p>
 *
 * <p>Description:</p>
 *
 * <p>Copyright: Copyright (c) 2007</p>
 *
 * <p>Organisation:</p>
 *
 * @author   undefined
 * @version  1.0
 */

public class GridLayoutTest extends JPanel {

	private GridLayout layout = new GridLayout(4, 0, 0, 0);

	private JLabel label0 = new JLabel();
	private JTextField textfield0 = new JTextField();
	private JCheckBox checkbox0 = new JCheckBox();
	private JScrollPane scrollpane0 = new JScrollPane();
	private JList list0 = new JList();

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	public GridLayoutTest() {
		doInit();
	}

	/**
	 * @param
	 *
	 * @return
	 *
	 * @exception
	 *
	 * @see
	 */
	private void doInit() {
		setLayout(layout);

		label0.setText("JLabel:");
		textfield0.setText("JTextField");
		checkbox0.setPreferredSize(new Dimension(114, 26));
		checkbox0.setText("JCheckBox");
		scrollpane0.getViewport().add(list0);

		add(label0);
		add(textfield0);
		add(checkbox0);
		add(scrollpane0);
	}

}
