/*---- Generated by CellsDesigner at 11.03.2008 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class HelloWorld extends JPanel {

     private double[][] constraints = {
          {CellsLayout.FILL, 20.0, },
          {CellsLayout.PREFERRED, CellsLayout.FILL, CellsLayout.PREFERRED, CellsLayout.PREFERRED, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private JLabel label1 = new JLabel();
     private JScrollPane scrollpane1 = new JScrollPane();
     private JTextArea scrollpane1_textarea1 = new JTextArea();
     private JButton button1 = new JButton();
     private JButton button2 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public HelloWorld() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          label1.setText("Hello");
          scrollpane1.getViewport().add(scrollpane1_textarea1);
          scrollpane1_textarea1.setText("World");
          button1.setMaximumSize(new Dimension(47, 23));
          button1.setMinimumSize(new Dimension(47, 23));
          button1.setPreferredSize(new Dimension(47, 23));
          button1.setText("Ok");
          button2.setText("Cancel");

          button1.addActionListener(new button1_ActionListener());

          add(label1, new CellsLayout.Cell(0, 0, true, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scrollpane1, new CellsLayout.Cell(0, 1, false, 0, 2, CellsLayout.LEFT, CellsLayout.TOP));
          add(button1, new CellsLayout.Cell(1, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(button2, new CellsLayout.Cell(1, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     *
     *
     */
     private class button1_ActionListener implements ActionListener {

          public void actionPerformed(ActionEvent e) {
          }
     }

}

