/*---- Generated by The Cells at 26.01.2009 ----*/

package org.nalizadeh.designer.examples;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTree;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;
import org.nalizadeh.designer.util.beans.JCalendar;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class Keep extends JPanel {

     private BorderLayout layout = new BorderLayout(4, 4);

     private double[][] panel2_constraints = {
          {20.0, },
          {60.0, CellsLayout.FILL, CellsLayout.FILL, }
     };

     private CellsLayout panel2_layout = new CellsLayout(panel2_constraints, 0, 0);

     private FlowLayout panel2_panel3_layout = new FlowLayout(FlowLayout.RIGHT, 0, 0);

     private BorderLayout splitpane1_panel4_layout = new BorderLayout(0, 0);

     private double[][] splitpane1_panel5_constraints = {
          {20.0, 20.0, 20.0, 20.0, CellsLayout.FILL, },
          {CellsLayout.PREFERRED, CellsLayout.FILL, }
     };

     private CellsLayout splitpane1_panel5_layout = new CellsLayout(splitpane1_panel5_constraints, 4, 4);

     private FlowLayout panel1_layout = new FlowLayout(FlowLayout.RIGHT, 4, 4);

     JPanel panel2 = new JPanel();
     JLabel panel2_label1 = new JLabel();
     JPanel panel2_panel3 = new JPanel();
     JCheckBox panel2_panel3_checkbox1 = new JCheckBox();
     JCheckBox panel2_panel3_checkbox2 = new JCheckBox();
     private JSplitPane splitpane1 = new JSplitPane();
     JPanel splitpane1_panel4 = new JPanel();
     JScrollPane splitpane1_panel4_scrollpane1 = new JScrollPane();
     JTree splitpane1_panel4_scrollpane1_tree1 = new JTree();
     JPanel splitpane1_panel5 = new JPanel();
     JLabel splitpane1_panel5_label2 = new JLabel();
     JTextField splitpane1_panel5_textfield1 = new JTextField();
     JLabel splitpane1_panel5_label3 = new JLabel();
     JTextField splitpane1_panel5_textfield2 = new JTextField();
     JLabel splitpane1_panel5_label4 = new JLabel();
     JTextField splitpane1_panel5_textfield3 = new JTextField();
     JLabel splitpane1_panel5_label5 = new JLabel();
     JTextField splitpane1_panel5_textfield4 = new JTextField();
     JLabel splitpane1_panel5_label6 = new JLabel();
     JScrollPane splitpane1_panel5_scrollpane2 = new JScrollPane();
     JTextArea splitpane1_panel5_scrollpane2_textarea1 = new JTextArea();
     JPanel panel1 = new JPanel();
     JButton panel1_button1 = new JButton();
     JButton panel1_button2 = new JButton();
     JButton panel1_button3 = new JButton();
     JCalendar panel1_calendar1 = new JCalendar();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public Keep() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          panel2_label1.setText("Keeps:");
          panel2_panel3_checkbox1.setText("Show All");
          panel2_panel3_checkbox2.setText("Show only Enableds");
          splitpane1.setLeftComponent(splitpane1_panel4);
          splitpane1.setRightComponent(splitpane1_panel5);
          splitpane1_panel4_scrollpane1.getViewport().add(splitpane1_panel4_scrollpane1_tree1);
          splitpane1_panel5_label2.setText("Name:");
          splitpane1_panel5_textfield1.setText("");
          splitpane1_panel5_label3.setText("User ID:");
          splitpane1_panel5_textfield2.setText("");
          splitpane1_panel5_label4.setText("Password:");
          splitpane1_panel5_textfield3.setText("");
          splitpane1_panel5_label5.setText("URL:");
          splitpane1_panel5_textfield4.setText("");
          splitpane1_panel5_label6.setText("Comments:");
          splitpane1_panel5_scrollpane2.getViewport().add(splitpane1_panel5_scrollpane2_textarea1);
          splitpane1_panel5_scrollpane2_textarea1.setText("");
          panel1_button1.setText("<< Prev");
          panel1_button2.setText("Next >>");
          panel1_button3.setText("Close");

          initPanel1();
          initPanel2();
          initPanel2_panel3();
          initSplitpane1_panel4();
          initSplitpane1_panel5();

          add(panel2, BorderLayout.NORTH);
          add(splitpane1, BorderLayout.CENTER);
          add(panel1, BorderLayout.SOUTH);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_button1);
          panel1_button1.setPreferredSize(new Dimension(84, 23));
          panel1.add(panel1_button2);
          panel1_button2.setPreferredSize(new Dimension(82, 23));
          panel1.add(panel1_button3);
          panel1_button3.setPreferredSize(new Dimension(71, 23));
          panel1.add(panel1_calendar1);
          panel1_calendar1.setPreferredSize(new Dimension(90, 22));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel2() {
          panel2.setLayout(panel2_layout);
          panel2.add(panel2_label1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel2.add(panel2_panel3, new CellsLayout.Cell(0, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel2_panel3() {
          panel2_panel3.setLayout(panel2_panel3_layout);
          panel2_panel3.add(panel2_panel3_checkbox1);
          panel2_panel3_checkbox1.setPreferredSize(new Dimension(84, 23));
          panel2_panel3.add(panel2_panel3_checkbox2);
          panel2_panel3_checkbox2.setPreferredSize(new Dimension(149, 23));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initSplitpane1_panel4() {
          splitpane1_panel4.setLayout(splitpane1_panel4_layout);
          splitpane1_panel4.add(splitpane1_panel4_scrollpane1, BorderLayout.CENTER);
          splitpane1.setLeftComponent(splitpane1_panel4);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initSplitpane1_panel5() {
          splitpane1_panel5.setLayout(splitpane1_panel5_layout);
          splitpane1_panel5.add(splitpane1_panel5_label2, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_textfield1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_label3, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_textfield2, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_label4, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_textfield3, new CellsLayout.Cell(2, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_label5, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_textfield4, new CellsLayout.Cell(3, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_label6, new CellsLayout.Cell(4, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel5.add(splitpane1_panel5_scrollpane2, new CellsLayout.Cell(4, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1.setRightComponent(splitpane1_panel5);
     }

}

