/*---- Generated by CellsDesigner at 29.12.2007 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class LayoutPanel extends JPanel {

     private double[][] constraints = {
          {10.0, 20.0, 20.0, 20.0, 20.0, 20.0, CellsLayout.FILL, CellsLayout.PREFERRED, },
          {CellsLayout.PREFERRED, 50.0, CellsLayout.PREFERRED, 50.0, CellsLayout.PREFERRED, 22.0, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private FlowLayout panel1_layout = new FlowLayout(FlowLayout.RIGHT, 4, 4);

     private JLabel lbLayout = new JLabel();
     private JTextArea tfLayout = new JTextArea();
     private JButton btLayout = new JButton();
     private JLabel lbHgap = new JLabel();
     private JSpinner spHgap = new JSpinner();
     private JLabel lbVgap = new JLabel();
     private JSpinner spVgap = new JSpinner();
     private JLabel lbRows = new JLabel();
     private JSpinner spRows = new JSpinner();
     private JLabel lbCols = new JLabel();
     private JSpinner spCols = new JSpinner();
     private JLabel lbAlg = new JLabel();
     private JComboBox coAlg = new JComboBox();
     private JLabel lbAxs = new JLabel();
     private JComboBox coAxs = new JComboBox();
     private JPanel panel1 = new JPanel();
     private JButton panel1_button1 = new JButton();
     private JButton panel1_button2 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public LayoutPanel() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          lbLayout.setName("lbLayout");
          lbLayout.setText("Layout:");
          tfLayout.setEditable(Boolean.FALSE);
          tfLayout.setName("tfLayout");
          tfLayout.setText("");
          btLayout.setName("btLayout");
          btLayout.setRequestFocusEnabled(Boolean.FALSE);
          btLayout.setText("...");
          lbHgap.setName("lbHgap");
          lbHgap.setText("HGap:");
          spHgap.setName("spHgap");
          lbVgap.setName("lbVgap");
          lbVgap.setText("VGap:");
          spVgap.setName("spVgap");
          lbRows.setName("lbRows");
          lbRows.setText("Rows:");
          spRows.setName("spRows");
          lbCols.setName("lbCols");
          lbCols.setText("Columns:");
          spCols.setName("spCols");
          lbAlg.setName("lbAlg");
          lbAlg.setText("Aligments:");
          coAlg.setName("coAlg");
          lbAxs.setName("lbAxs");
          lbAxs.setText("Axis:");
          coAxs.setName("coAxs");
          panel1_button1.setText("ok");
          panel1_button2.setText("cancel");

          initPanel1();

          add(lbLayout, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tfLayout, new CellsLayout.Cell(1, 1, false, 0, 3, CellsLayout.LEFT, CellsLayout.TOP));
          add(btLayout, new CellsLayout.Cell(1, 5, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbHgap, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(spHgap, new CellsLayout.Cell(2, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbVgap, new CellsLayout.Cell(2, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(spVgap, new CellsLayout.Cell(2, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbRows, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(spRows, new CellsLayout.Cell(3, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbCols, new CellsLayout.Cell(3, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(spCols, new CellsLayout.Cell(3, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbAlg, new CellsLayout.Cell(4, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(coAlg, new CellsLayout.Cell(4, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbAxs, new CellsLayout.Cell(5, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(coAxs, new CellsLayout.Cell(5, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(panel1, new CellsLayout.Cell(7, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_button1);
          panel1_button1.setPreferredSize(new Dimension(69, 23));
          panel1.add(panel1_button2);
          panel1_button2.setPreferredSize(new Dimension(69, 23));
     }

}

