/*---- Generated by CellsDesigner at 15.01.2008 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class NestedTest extends JPanel {

     private LayoutManager layout = null;

     private double[][] splitpane1_panel2_constraints = {
          {20.0, 20.0, 20.0, },
          {60.0, 99.0, }
     };

     private CellsLayout splitpane1_panel2_layout = new CellsLayout(splitpane1_panel2_constraints, 4, 4);

     private LayoutManager splitpane1_panel3_layout = null;

     private double[][] panel1_constraints = {
          {CellsLayout.FILL, },
          {130.0, CellsLayout.FILL, }
     };

     private CellsLayout panel1_layout = new CellsLayout(panel1_constraints, 4, 4);

     private FlowLayout panel1_panel1_layout = new FlowLayout(FlowLayout.LEFT, 4, 4);

     private double[][] panel1_panel1_panel1_constraints = {
          {20.0, 20.0, 20.0, },
          {60.0, 99.0, }
     };

     private CellsLayout panel1_panel1_panel1_layout = new CellsLayout(panel1_panel1_panel1_constraints, 4, 4);

     private JSplitPane splitpane1 = new JSplitPane();
     private JPanel splitpane1_panel2 = new JPanel();
     private JTextField splitpane1_panel2_textfield1 = new JTextField();
     private JLabel splitpane1_panel2_label2 = new JLabel();
     private JRadioButton splitpane1_panel2_radiobutton1 = new JRadioButton();
     private JLabel splitpane1_panel2_label1 = new JLabel();
     private JPanel splitpane1_panel3 = new JPanel();
     private JLabel splitpane1_panel3_label1 = new JLabel();
     private JScrollPane splitpane1_panel3_scrollpane1 = new JScrollPane();
     private JTree splitpane1_panel3_scrollpane1_tree1 = new JTree();
     private JPanel panel1 = new JPanel();
     private JCheckBox panel1_checkbox1 = new JCheckBox();
     private JPanel panel1_panel1 = new JPanel();
     private JLabel panel1_panel1_label1 = new JLabel();
     private JButton panel1_panel1_button1 = new JButton();
     private JPanel panel1_panel1_panel1 = new JPanel();
     private JLabel panel1_panel1_panel1_label2 = new JLabel();
     private JTextField panel1_panel1_panel1_textfield1 = new JTextField();
     private JLabel panel1_panel1_panel1_label3 = new JLabel();
     private JRadioButton panel1_panel1_panel1_radiobutton1 = new JRadioButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public NestedTest() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          splitpane1.setLeftComponent(splitpane1_panel2);
          splitpane1.setRightComponent(splitpane1_panel3);
          splitpane1_panel2.setBackground(new Color(204, 204, 255));
          splitpane1_panel2_textfield1.setText("JTextField");
          splitpane1_panel2_label2.setEnabled(Boolean.FALSE);
          splitpane1_panel2_label2.setText("JLabel:");
          splitpane1_panel2_radiobutton1.setText("JRadioButton");
          splitpane1_panel2_label1.setText("JLabel:");
          splitpane1_panel3.setBackground(new Color(255, 204, 102));
          splitpane1_panel3_label1.setText("JLabel:");
          splitpane1_panel3_scrollpane1.getViewport().add(splitpane1_panel3_scrollpane1_tree1);
          panel1.setBackground(new Color(255, 153, 153));
          panel1_checkbox1.setText("JCheckBox");
          panel1_panel1.setBackground(new Color(135, 164, 135));
          panel1_panel1_label1.setPreferredSize(new Dimension(34, 20));
          panel1_panel1_label1.setText("JLabel:");
          panel1_panel1_button1.setFont(new Font("Tahoma Fett", 1, 11));
          panel1_panel1_button1.setPreferredSize(new Dimension(97, 23));
          panel1_panel1_button1.setText("JButton");
          panel1_panel1_panel1.setBackground(new Color(204, 204, 255));
          panel1_panel1_panel1.setPreferredSize(new Dimension(171, 76));
          panel1_panel1_panel1_label2.setText("JLabel:");
          panel1_panel1_panel1_textfield1.setText("JTextField");
          panel1_panel1_panel1_label3.setEnabled(Boolean.FALSE);
          panel1_panel1_panel1_label3.setText("JLabel:");
          panel1_panel1_panel1_radiobutton1.setText("JRadioButton");

          initPanel1();
          initPanel1_panel1();
          initPanel1_panel1_panel1();
          initSplitpane1_panel2();
          initSplitpane1_panel3();

          add(splitpane1);
          splitpane1.setBounds(new Rectangle(110, 199, 352, 151));
          add(panel1);
          panel1.setBounds(new Rectangle(17, 31, 496, 131));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_checkbox1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1.add(panel1_panel1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1_panel1() {
          panel1_panel1.setLayout(panel1_panel1_layout);
          panel1_panel1.add(panel1_panel1_label1);
          panel1_panel1_label1.setPreferredSize(new Dimension(34, 20));
          panel1_panel1.add(panel1_panel1_button1);
          panel1_panel1_button1.setPreferredSize(new Dimension(97, 23));
          panel1_panel1.add(panel1_panel1_panel1);
          panel1_panel1_panel1.setPreferredSize(new Dimension(171, 76));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1_panel1_panel1() {
          panel1_panel1_panel1.setLayout(panel1_panel1_panel1_layout);
          panel1_panel1_panel1.add(panel1_panel1_panel1_label2, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1_panel1_panel1.add(panel1_panel1_panel1_textfield1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1_panel1_panel1.add(panel1_panel1_panel1_label3, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1_panel1_panel1.add(panel1_panel1_panel1_radiobutton1, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initSplitpane1_panel2() {
          splitpane1_panel2.setLayout(splitpane1_panel2_layout);
          splitpane1_panel2.add(splitpane1_panel2_textfield1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel2.add(splitpane1_panel2_label2, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel2.add(splitpane1_panel2_radiobutton1, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1_panel2.add(splitpane1_panel2_label1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          splitpane1.setLeftComponent(splitpane1_panel2);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initSplitpane1_panel3() {
          splitpane1_panel3.setLayout(splitpane1_panel3_layout);
          splitpane1_panel3.add(splitpane1_panel3_label1);
          splitpane1_panel3_label1.setBounds(new Rectangle(32, 13, 34, 20));
          splitpane1_panel3.add(splitpane1_panel3_scrollpane1);
          splitpane1_panel3_scrollpane1.setBounds(new Rectangle(27, 36, 128, 99));
          splitpane1.setRightComponent(splitpane1_panel3);
     }

}

