/*---- Generated by The Cells at 06.03.2009 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:<p>
*
* <p>Description:<p>
*
* <p>Copyright: Copyright (c) 2007<p>
*
* <p>Organisation:<p>
*
* @author   undefined
* @version  1.0
*/

public class SearchPanel extends JPanel {

     private double[][] constraints = {
          {20.0, 28.0, 9.0, 20.0, CellsLayout.FILL, 32.0, },
          {60.0, 60.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private double[][] panel2_constraints = {
          {20.0, 20.0, },
          {CellsLayout.FILL, 80.0, }
     };

     private CellsLayout panel2_layout = new CellsLayout(panel2_constraints, 4, 4);

     private FlowLayout panel1_layout = new FlowLayout(FlowLayout.RIGHT, 5, 5);

     private JLabel label1 = new JLabel();
     private JTextField textfield1 = new JTextField();
     JPanel panel2 = new JPanel();
     private JButton panel2_button1 = new JButton();
     private JButton panel2_button2 = new JButton();
     private JLabel label2 = new JLabel();
     private JScrollPane scrollpane1 = new JScrollPane();
     private JTable scrollpane1_table1 = new JTable();
     JPanel panel1 = new JPanel();
     private JButton panel1_button1 = new JButton();
     private JButton panel1_button2 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public SearchPanel() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          label1.setText("Region:");
          textfield1.setText("");
          panel2_button1.setText("Search");
          panel2_button2.setText("Restore");
          label2.setFont(new Font("Tahoma Fett", 1, 11));
          label2.setText("Results:");
          scrollpane1.getViewport().add(scrollpane1_table1);
          scrollpane1_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    
               },
               new String [] {
                    "Test Column", "Title 2", "Title 3", "Title 4", 
               }
          ));
          panel1_button1.setText("Cancel");
          panel1_button2.setText("Ok");

          initPanel1();
          initPanel2();

          add(label1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(textfield1, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(panel2, new CellsLayout.Cell(0, 3, false, 1, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(label2, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scrollpane1, new CellsLayout.Cell(3, 1, false, 1, 2, CellsLayout.LEFT, CellsLayout.TOP));
          add(panel1, new CellsLayout.Cell(5, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(panel1_button1);
          panel1_button1.setPreferredSize(new Dimension(65, 23));
          panel1.add(panel1_button2);
          panel1_button2.setPreferredSize(new Dimension(45, 23));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel2() {
          panel2.setLayout(panel2_layout);
          panel2.add(panel2_button1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel2.add(panel2_button2, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

}

