/*---- Generated by The Cells at 02.10.2013 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:<p>
*
* <p>Description:<p>
*
* <p>Copyright: Copyright (c) 2007<p>
*
* <p>Organisation:<p>
*
* @author   undefined
* @version  1.0
*/

public class Swing extends JPanel {

     private double[][] constraints = {
          {20.0, 35.0, CellsLayout.FILL, 30.0, },
          {110.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private double[][] tabbedpane1_panel1_constraints = {
          {20.0, CellsLayout.FILL, },
          {60.0, CellsLayout.FILL, }
     };

     private CellsLayout tabbedpane1_panel1_layout = new CellsLayout(tabbedpane1_panel1_constraints, 4, 4);

     private double[][] tabbedpane1_panel2_constraints = {
          {20.0, 20.0, 20.0, CellsLayout.FILL, },
          {60.0, 60.0, 60.0, 60.0, }
     };

     private CellsLayout tabbedpane1_panel2_layout = new CellsLayout(tabbedpane1_panel2_constraints, 4, 4);

     JLabel label1 = new JLabel();
     JTextField textfield1 = new JTextField();
     JTabbedPane tabbedpane1 = new JTabbedPane();
     JPanel tabbedpane1_panel1 = new JPanel();
     JLabel tabbedpane1_panel1_label2 = new JLabel();
     JScrollPane tabbedpane1_panel1_scrollpane1 = new JScrollPane();
     JTable tabbedpane1_panel1_scrollpane1_table1 = new JTable();
     JPanel tabbedpane1_panel2 = new JPanel();
     JLabel tabbedpane1_panel2_label3 = new JLabel();
     JTextField tabbedpane1_panel2_textfield2 = new JTextField();
     JLabel tabbedpane1_panel2_label4 = new JLabel();
     JTextField tabbedpane1_panel2_textfield3 = new JTextField();
     JToggleButton tabbedpane1_panel2_togglebutton1 = new JToggleButton();
     JLabel tabbedpane1_panel2_label5 = new JLabel();
     JScrollPane tabbedpane1_panel2_scrollpane2 = new JScrollPane();
     JList tabbedpane1_panel2_scrollpane2_list1 = new JList();
     JButton button1 = new JButton();
     JButton button2 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public Swing() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          label1.setFont(new Font("Tunga Bold", 1, 28));
          label1.setText("Operation:");
          textfield1.setText("JTextField:");
          tabbedpane1.setFont(new Font("Tahoma", 0, 13));
          tabbedpane1_panel1_label2.setText("JLabel:");
          tabbedpane1_panel1_scrollpane1.setFont(new Font("Tahoma", 0, 13));
          tabbedpane1_panel1_scrollpane1.getViewport().add(tabbedpane1_panel1_scrollpane1_table1);
          tabbedpane1_panel1_scrollpane1_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4", 
               }
          ));
          tabbedpane1_panel2_label3.setText("JLabel:");
          tabbedpane1_panel2_textfield2.setText("JTextField:");
          tabbedpane1_panel2_label4.setText("JLabel:");
          tabbedpane1_panel2_textfield3.setText("JTextField:");
          tabbedpane1_panel2_togglebutton1.setText("JToggleButton:");
          tabbedpane1_panel2_label5.setText("JLabel:");
          tabbedpane1_panel2_scrollpane2.getViewport().add(tabbedpane1_panel2_scrollpane2_list1);
          button1.setText("JButton:");
          button2.setText("JButton:");

          initTabbedpane1_panel1();
          initTabbedpane1_panel2();

          add(label1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(textfield1, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(tabbedpane1, new CellsLayout.Cell(2, 0, false, 0, 2, CellsLayout.LEFT, CellsLayout.TOP));
          add(button1, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(button2, new CellsLayout.Cell(3, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel1() {
          tabbedpane1_panel1.setLayout(tabbedpane1_panel1_layout);
          tabbedpane1_panel1.add(tabbedpane1_panel1_label2, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel1.add(tabbedpane1_panel1_scrollpane1, new CellsLayout.Cell(1, 0, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1.add("tab1", tabbedpane1_panel1);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel2() {
          tabbedpane1_panel2.setLayout(tabbedpane1_panel2_layout);
          tabbedpane1_panel2.add(tabbedpane1_panel2_label3, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_textfield2, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_label4, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_textfield3, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_togglebutton1, new CellsLayout.Cell(2, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_label5, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1_panel2.add(tabbedpane1_panel2_scrollpane2, new CellsLayout.Cell(3, 1, false, 0, 2, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1.add("tab2", tabbedpane1_panel2);
     }

}

