/*---- Generated by CellsDesigner at 29.11.2007 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class TheCellsForm extends JPanel {

     private double[][] constraints = {
          {20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, CellsLayout.FILL, },
          {CellsLayout.FILL, 20.0, 20.0, 60.0, 60.0, 60.0, 60.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private double[][] panel3_constraints = {
          {20.0, 20.0, },
          {60.0, 20.0, 60.0, CellsLayout.PREFERRED, 60.0, }
     };

     private CellsLayout panel3_layout = new CellsLayout(panel3_constraints, 4, 4);

     private double[][] tabbedpane1_panel1_constraints = {
          {CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout tabbedpane1_panel1_layout = new CellsLayout(tabbedpane1_panel1_constraints, 0, 0);

     private LayoutManager tabbedpane1_panel2_layout = null;

     private JPanel panel3 = new JPanel();
     private JCheckBox panel3_togglebutton1 = new JCheckBox();
     private JLabel panel3_label1 = new JLabel();
     private JTextField panel3_textfield1 = new JTextField();
     private JButton panel3_button1 = new JButton();
     private JLabel label1 = new JLabel();
     private JTabbedPane tabbedpane1 = new JTabbedPane();
     private JPanel tabbedpane1_panel1 = new JPanel();
     private JScrollPane tabbedpane1_panel1_scrollpane1 = new JScrollPane();
     private JTable tabbedpane1_panel1_scrollpane1_table1 = new JTable();
     private JPanel tabbedpane1_panel2 = new JPanel();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public TheCellsForm() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          panel3_togglebutton1.setText("use update");
          panel3_label1.setText("Count:");
          panel3_textfield1.setText("");
          panel3_button1.setText("bx");
          label1.setFont(new Font("Tahoma Fett", 1, 11));
          label1.setText("Acount:");
          tabbedpane1_panel1_scrollpane1.getViewport().add(tabbedpane1_panel1_scrollpane1_table1);
          tabbedpane1_panel1_scrollpane1_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));

          initPanel3();
          initTabbedpane1_panel1();
          initTabbedpane1_panel2();

          add(panel3, new CellsLayout.Cell(6, 0, false, 1, 6, CellsLayout.LEFT, CellsLayout.TOP));
          add(label1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tabbedpane1, new CellsLayout.Cell(1, 0, false, 4, 4, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel3() {
          panel3.setLayout(panel3_layout);
          panel3.add(panel3_togglebutton1, new CellsLayout.Cell(0, 0, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          panel3.add(panel3_label1, new CellsLayout.Cell(0, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel3.add(panel3_textfield1, new CellsLayout.Cell(0, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel3.add(panel3_button1, new CellsLayout.Cell(1, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel1() {
          tabbedpane1_panel1.setLayout(tabbedpane1_panel1_layout);
          tabbedpane1_panel1.add(tabbedpane1_panel1_scrollpane1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tabbedpane1.add("Search", tabbedpane1_panel1);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTabbedpane1_panel2() {
          tabbedpane1_panel2.setLayout(tabbedpane1_panel2_layout);
          tabbedpane1.add("Parameter", tabbedpane1_panel2);
     }

}

