/*---- Generated by CellsDesigner at 12.01.2008 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Font;
import java.awt.LayoutManager;
import java.awt.Rectangle;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:</p>
*
* <p>Description:</p>
*
* <p>Copyright: Copyright (c) 2007</p>
*
* <p>Organisation:</p>
*
* @author   undefined
* @version  1.0
*/

public class TkKonto extends JPanel {

     private double[][] constraints = {
          {20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 10.0, 20.0, CellsLayout.FILL, CellsLayout.PREFERRED, },
          {162.0, 60.0, 20.0, 60.0, 60.0, 20.0, 77.0, 60.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 4, 4);

     private double[][] paKlaeren1_constraints = {
          {CellsLayout.PREFERRED, 8.0, CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout paKlaeren1_layout = new CellsLayout(paKlaeren1_constraints, 4, 4);

     private double[][] paKlaeren5_constraints = {
          {20.0, },
          {158.0, 20.0, 90.0, 60.0, 60.0, 20.0, 20.0, }
     };

     private CellsLayout paKlaeren5_layout = new CellsLayout(paKlaeren5_constraints, 4, 4);

     private double[][] paKlaeren1_tabbedpane1_panel6_constraints = {
          {CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout paKlaeren1_tabbedpane1_panel6_layout = new CellsLayout(paKlaeren1_tabbedpane1_panel6_constraints, 0, 0);

     private double[][] paKlaeren3_constraints = {
          {CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout paKlaeren3_layout = new CellsLayout(paKlaeren3_constraints, 0, 0);

     private double[][] paKlaeren4_constraints = {
          {CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout paKlaeren4_layout = new CellsLayout(paKlaeren4_constraints, 0, 0);

     private LayoutManager paKlaeren1_tabbedpane1_panel7_layout = null;

     private double[][] paKlaeren2_constraints = {
          {20.0, 20.0, 20.0, CellsLayout.FILL, 10.0, 20.0, 10.0, 20.0, 20.0, 20.0, 20.0, 10.0, },
          {133.0, 90.0, 20.0, 20.0, 20.0, 20.0, 149.0, 129.0, 20.0, 20.0, CellsLayout.FILL, }
     };

     private CellsLayout paKlaeren2_layout = new CellsLayout(paKlaeren2_constraints, 4, 4);

     private double[][] paKlaeren2_panel1_constraints = {
          {20.0, 20.0, 20.0, 20.0, 20.0, CellsLayout.FILL, },
          {CellsLayout.FILL, 129.0, }
     };

     private CellsLayout paKlaeren2_panel1_layout = new CellsLayout(paKlaeren2_panel1_constraints, 4, 4);

     private double[][] panel1_constraints = {
          {20.0, },
          {CellsLayout.FILL, CellsLayout.PREFERRED, CellsLayout.PREFERRED, CellsLayout.PREFERRED, }
     };

     private CellsLayout panel1_layout = new CellsLayout(panel1_constraints, 4, 4);

     private JLabel lbZablstapel = new JLabel();
     private JTextField txZahlstapel = new JTextField();
     private JLabel lbPosition = new JLabel();
     private JTextField txPosition = new JTextField();
     private JLabel lbZahlungsdaten = new JLabel();
     private JLabel lbKonto = new JLabel();
     private JTextField txKonto = new JTextField();
     private JLabel lbBlz = new JLabel();
     private JTextField txBlz = new JTextField();
     private JLabel lbAufgb = new JLabel();
     private JTextField tcAufgb = new JTextField();
     private JLabel lbVerw = new JLabel();
     private JTextField txVerw = new JTextField();
     private JLabel lbEzv = new JLabel();
     private JTextField textfield7 = new JTextField();
     private JLabel lbMeldMash = new JLabel();
     private JScrollPane scVerMash = new JScrollPane();
     private JTextArea taVerMash = new JTextArea();
     private JLabel lbMeldMan = new JLabel();
     private JScrollPane scMeldMan = new JScrollPane();
     private JTextArea taMeldMan = new JTextArea();
     private JLabel lbZahlbetrag = new JLabel();
     private JTextField txZahlbetrag = new JTextField();
     private JLabel lbRest = new JLabel();
     private JTextField txRest = new JTextField();
     private JCheckBox chAkonto = new JCheckBox();
     private JLabel lbHerkunft = new JLabel();
     private JComboBox coHerkunft = new JComboBox();
     private JLabel lbKlaeren = new JLabel();
     private JTabbedPane tbKlaeren = new JTabbedPane();
     private JPanel paKlaeren1 = new JPanel();
     private JPanel paKlaeren5 = new JPanel();
     private JButton paKlaeren5_button3 = new JButton();
     private JLabel lbVersNr = new JLabel();
     private JTextField txVersNr = new JTextField();
     private JButton paKlaeren5_button1 = new JButton();
     private JButton paKlaeren5_button2 = new JButton();
     private JTabbedPane paKlaeren1_tabbedpane1 = new JTabbedPane();
     private JPanel paKlaeren1_tabbedpane1_panel6 = new JPanel();
     private JSplitPane spKlaeren1 = new JSplitPane();
     private JPanel paKlaeren3 = new JPanel();
     private JScrollPane scKlaeren1 = new JScrollPane();
     private JTable taKlaeren1 = new JTable();
     private JPanel paKlaeren4 = new JPanel();
     private JScrollPane scKlaeren2 = new JScrollPane();
     private JTable taKlaeren2 = new JTable();
     private JPanel paKlaeren1_tabbedpane1_panel7 = new JPanel();
     private JPanel paKlaeren2 = new JPanel();
     private JScrollPane paKlaeren2_scrollpane1 = new JScrollPane();
     private JTable paKlaeren2_scrollpane1_table1 = new JTable();
     private JLabel lbTeilbetrag = new JLabel();
     private JTextField tfTeilbetrag = new JTextField();
     private JPanel paKlaeren2_panel1 = new JPanel();
     private JButton paKlaeren2_panel1_button1 = new JButton();
     private JButton paKlaeren2_panel1_button2 = new JButton();
     private JButton paKlaeren2_panel1_button3 = new JButton();
     private JButton paKlaeren2_panel1_button4 = new JButton();
     private JButton paKlaeren2_panel1_button5 = new JButton();
     private JLabel lbArbeitgeberbeitrag = new JLabel();
     private JLabel lbVersObj = new JLabel();
     private JTextField tfVersObj = new JTextField();
     private JButton btVersObj1 = new JButton();
     private JButton btVersObj2 = new JButton();
     private JLabel lbAbrechSatz = new JLabel();
     private JTextField tfAbrechSatz = new JTextField();
     private JButton btAbrechSatz1 = new JButton();
     private JButton btAbrechSatz2 = new JButton();
     private JLabel lbBeitragsmonat = new JLabel();
     private JTextField tfBeitragsmonat = new JTextField();
     private JLabel lbGpPos = new JLabel();
     private JTextField tfGpPos = new JTextField();
     private JButton btGpPos1 = new JButton();
     private JButton btGpPos2 = new JButton();
     private JLabel lbInsolvenz = new JLabel();
     private JTextField tfInsolvenz = new JTextField();
     private JPanel panel1 = new JPanel();
     private JButton btAusgleichen = new JButton();
     private JButton btAbbrechen = new JButton();
     private JButton panel1_button3 = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public TkKonto() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          lbZablstapel.setName("lbZablstapel");
          lbZablstapel.setText("Zahlstapel:");
          txZahlstapel.setEditable(Boolean.FALSE);
          txZahlstapel.setName("txZahlstapel");
          txZahlstapel.setText("");
          lbPosition.setName("lbPosition");
          lbPosition.setText("Position:");
          txPosition.setEditable(Boolean.FALSE);
          txPosition.setName("txPosition");
          txPosition.setText("");
          lbZahlungsdaten.setFont(new Font("Tahoma Fett", 1, 11));
          lbZahlungsdaten.setName("lbZahlungsdaten");
          lbZahlungsdaten.setText("Zahlungsdaten");
          lbKonto.setName("lbKonto");
          lbKonto.setText("Kontonummer:");
          txKonto.setEditable(Boolean.FALSE);
          txKonto.setName("txKonto");
          txKonto.setText("");
          lbBlz.setName("lbBlz");
          lbBlz.setText("Bankleitzahl:");
          txBlz.setEditable(Boolean.FALSE);
          txBlz.setName("txBlz");
          txBlz.setText("");
          lbAufgb.setName("lbAufgb");
          lbAufgb.setText("Auftraggeber:");
          tcAufgb.setEditable(Boolean.FALSE);
          tcAufgb.setName("tcAufgb");
          tcAufgb.setText("");
          lbVerw.setName("lbVerw");
          lbVerw.setText("Verwendungszweck:");
          txVerw.setEditable(Boolean.FALSE);
          txVerw.setName("txVerw");
          txVerw.setText("");
          lbEzv.setName("lbEzv");
          lbEzv.setText("EZV-Refererenz-Nr:");
          textfield7.setEditable(Boolean.FALSE);
          textfield7.setText("");
          lbMeldMash.setName("lbMeldMash");
          lbMeldMash.setText("Verarbeitungsmeldungen masch.:");
          scVerMash.getViewport().add(taVerMash);
          taVerMash.setText("");
          lbMeldMan.setName("lbMeldMan");
          lbMeldMan.setText("Verarbeitungsmeldungen man.:");
          scMeldMan.getViewport().add(taMeldMan);
          taMeldMan.setText("");
          lbZahlbetrag.setName("lbZahlbetrag");
          lbZahlbetrag.setText("Zahlbetrag:");
          txZahlbetrag.setName("txZahlbetrag");
          txZahlbetrag.setText("700,00 EUR");
          lbRest.setName("lbRest");
          lbRest.setText("Restbetrag:");
          txRest.setEditable(Boolean.FALSE);
          txRest.setName("txRest");
          txRest.setText("");
          chAkonto.setName("chAkonto");
          chAkonto.setText("Akonto");
          lbHerkunft.setName("lbHerkunft");
          lbHerkunft.setText("Herkunft:");
          coHerkunft.setName("coHerkunft");
          lbKlaeren.setFont(new Font("Tahoma Fett", 1, 11));
          lbKlaeren.setName("lbKlaeren");
          lbKlaeren.setText("Klären");
          tbKlaeren.setName("tbKlaeren");
          paKlaeren5_button3.setText("weiteres TK-Konto klären");
          lbVersNr.setText("Versicherten-Nr.:");
          txVersNr.setText("");
          paKlaeren5_button1.setText("...");
          paKlaeren5_button2.setText("...");
          spKlaeren1.setLeftComponent(paKlaeren3);
          spKlaeren1.setRightComponent(paKlaeren4);
          scKlaeren1.getViewport().add(taKlaeren1);
          taKlaeren1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          scKlaeren2.getViewport().add(taKlaeren2);
          taKlaeren2.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          paKlaeren2_scrollpane1.getViewport().add(paKlaeren2_scrollpane1_table1);
          paKlaeren2_scrollpane1_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          lbTeilbetrag.setText("(Teil-)Betrag:");
          tfTeilbetrag.setText("");
          paKlaeren2_panel1_button1.setText("Neue Einzelzeile");
          paKlaeren2_panel1_button2.setEnabled(Boolean.FALSE);
          paKlaeren2_panel1_button2.setText("Lösche Zeile");
          paKlaeren2_panel1_button3.setEnabled(Boolean.FALSE);
          paKlaeren2_panel1_button3.setText("Verwerfen");
          paKlaeren2_panel1_button4.setEnabled(Boolean.FALSE);
          paKlaeren2_panel1_button4.setText("Akzeptieren");
          paKlaeren2_panel1_button5.setEnabled(Boolean.FALSE);
          paKlaeren2_panel1_button5.setText("Akzeptieren & Neu");
          lbArbeitgeberbeitrag.setFont(new Font("Tahoma Fett", 1, 11));
          lbArbeitgeberbeitrag.setText("Arbeitgeberbeitrag");
          lbVersObj.setFont(new Font("Tahoma Fett", 1, 11));
          lbVersObj.setText("Versicherungsobjekt");
          tfVersObj.setText("");
          btVersObj1.setText("...");
          btVersObj2.setText("...");
          lbAbrechSatz.setText("Abrechnungssatz:");
          tfAbrechSatz.setText("");
          btAbrechSatz1.setText("...");
          btAbrechSatz2.setText("...");
          lbBeitragsmonat.setText("Beitragsmonat:");
          tfBeitragsmonat.setText("");
          lbGpPos.setFont(new Font("Tahoma Fett", 1, 11));
          lbGpPos.setText("Geschäftspartnerposition");
          tfGpPos.setText("");
          btGpPos1.setText("...");
          btGpPos2.setText("...");
          lbInsolvenz.setText("Rückzahlung Insolvenzgeld:");
          tfInsolvenz.setText("");
          btAusgleichen.setName("btAusgleichen");
          btAusgleichen.setText("Ausgleichen");
          btAbbrechen.setName("btAbbrechen");
          btAbbrechen.setText("Abbrechen");
          panel1_button3.setText("Fertigstellen");

          initPaKlaeren1();
          initPaKlaeren1_tabbedpane1_panel6();
          initPaKlaeren1_tabbedpane1_panel7();
          initPaKlaeren2();
          initPaKlaeren2_panel1();
          initPaKlaeren3();
          initPaKlaeren4();
          initPaKlaeren5();
          initPanel1();

          add(lbZablstapel, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txZahlstapel, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbPosition, new CellsLayout.Cell(0, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txPosition, new CellsLayout.Cell(0, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbZahlungsdaten, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbKonto, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txKonto, new CellsLayout.Cell(2, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbBlz, new CellsLayout.Cell(2, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txBlz, new CellsLayout.Cell(2, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbAufgb, new CellsLayout.Cell(2, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tcAufgb, new CellsLayout.Cell(2, 7, false, 0, 2, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbVerw, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txVerw, new CellsLayout.Cell(3, 1, false, 0, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbEzv, new CellsLayout.Cell(4, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(textfield7, new CellsLayout.Cell(4, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbMeldMash, new CellsLayout.Cell(5, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scVerMash, new CellsLayout.Cell(5, 1, false, 2, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbMeldMan, new CellsLayout.Cell(8, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scMeldMan, new CellsLayout.Cell(8, 1, false, 2, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbZahlbetrag, new CellsLayout.Cell(11, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txZahlbetrag, new CellsLayout.Cell(11, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbRest, new CellsLayout.Cell(11, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txRest, new CellsLayout.Cell(11, 4, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(chAkonto, new CellsLayout.Cell(11, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbHerkunft, new CellsLayout.Cell(11, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(coHerkunft, new CellsLayout.Cell(11, 8, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbKlaeren, new CellsLayout.Cell(13, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tbKlaeren, new CellsLayout.Cell(14, 0, false, 0, 9, CellsLayout.LEFT, CellsLayout.TOP));
          add(panel1, new CellsLayout.Cell(15, 4, false, 0, 5, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren1() {
          paKlaeren1.setLayout(paKlaeren1_layout);
          paKlaeren1.add(paKlaeren5, new CellsLayout.Cell(0, 0, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren1.add(paKlaeren1_tabbedpane1, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren.add("Auf TK-Konto", paKlaeren1);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren1_tabbedpane1_panel6() {
          paKlaeren1_tabbedpane1_panel6.setLayout(paKlaeren1_tabbedpane1_panel6_layout);
          paKlaeren1_tabbedpane1_panel6.add(spKlaeren1, new CellsLayout.Cell(0, 0, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren1_tabbedpane1.add("Meier, Heinrich", paKlaeren1_tabbedpane1_panel6);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren1_tabbedpane1_panel7() {
          paKlaeren1_tabbedpane1_panel7.setLayout(paKlaeren1_tabbedpane1_panel7_layout);
          paKlaeren1_tabbedpane1.add("Zausel, Frank", paKlaeren1_tabbedpane1_panel7);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren2() {
          paKlaeren2.setLayout(paKlaeren2_layout);
          paKlaeren2.add(paKlaeren2_scrollpane1, new CellsLayout.Cell(0, 0, false, 3, 10, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbTeilbetrag, new CellsLayout.Cell(5, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfTeilbetrag, new CellsLayout.Cell(5, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(paKlaeren2_panel1, new CellsLayout.Cell(5, 10, false, 5, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbArbeitgeberbeitrag, new CellsLayout.Cell(7, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbVersObj, new CellsLayout.Cell(7, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfVersObj, new CellsLayout.Cell(7, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btVersObj1, new CellsLayout.Cell(7, 8, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btVersObj2, new CellsLayout.Cell(7, 9, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbAbrechSatz, new CellsLayout.Cell(8, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfAbrechSatz, new CellsLayout.Cell(8, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btAbrechSatz1, new CellsLayout.Cell(8, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btAbrechSatz2, new CellsLayout.Cell(8, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbBeitragsmonat, new CellsLayout.Cell(9, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfBeitragsmonat, new CellsLayout.Cell(9, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbGpPos, new CellsLayout.Cell(9, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfGpPos, new CellsLayout.Cell(9, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btGpPos1, new CellsLayout.Cell(9, 8, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(btGpPos2, new CellsLayout.Cell(9, 9, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(lbInsolvenz, new CellsLayout.Cell(10, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2.add(tfInsolvenz, new CellsLayout.Cell(10, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren.add("Auf Vertragskonto / Geschäftspartnerkonto", paKlaeren2);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren2_panel1() {
          paKlaeren2_panel1.setLayout(paKlaeren2_panel1_layout);
          paKlaeren2_panel1.add(paKlaeren2_panel1_button1, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2_panel1.add(paKlaeren2_panel1_button2, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2_panel1.add(paKlaeren2_panel1_button3, new CellsLayout.Cell(2, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2_panel1.add(paKlaeren2_panel1_button4, new CellsLayout.Cell(3, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren2_panel1.add(paKlaeren2_panel1_button5, new CellsLayout.Cell(4, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren3() {
          paKlaeren3.setLayout(paKlaeren3_layout);
          paKlaeren3.add(scKlaeren1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          spKlaeren1.setLeftComponent(paKlaeren3);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren4() {
          paKlaeren4.setLayout(paKlaeren4_layout);
          paKlaeren4.add(scKlaeren2, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          spKlaeren1.setRightComponent(paKlaeren4);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPaKlaeren5() {
          paKlaeren5.setLayout(paKlaeren5_layout);
          paKlaeren5.add(paKlaeren5_button3, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren5.add(lbVersNr, new CellsLayout.Cell(0, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren5.add(txVersNr, new CellsLayout.Cell(0, 3, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren5.add(paKlaeren5_button1, new CellsLayout.Cell(0, 5, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          paKlaeren5.add(paKlaeren5_button2, new CellsLayout.Cell(0, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel1() {
          panel1.setLayout(panel1_layout);
          panel1.add(btAusgleichen, new CellsLayout.Cell(0, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1.add(btAbbrechen, new CellsLayout.Cell(0, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel1.add(panel1_button3, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

}

