/*---- Generated by The Cells at 19.12.2013 ----*/

package org.nalizadeh.designer.examples;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.nalizadeh.designer.layouts.cellslayout.CellsLayout;

/**
* <p>Title:<p>
*
* <p>Description:<p>
*
* <p>Copyright: Copyright (c) 2007<p>
*
* <p>Organisation:<p>
*
* @author   undefined
* @version  1.0
*/

public class WebSwing extends JPanel {

     private double[][] constraints = {
          {20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 10.0, 20.0, CellsLayout.FILL, 25.0, },
          {162.0, 60.0, 20.0, 60.0, 60.0, 20.0, 77.0, 60.0, 60.0, CellsLayout.FILL, }
     };

     private CellsLayout layout = new CellsLayout(constraints, 8, 8);

     private double[][] tbKlaeren_panel1_constraints = {
          {CellsLayout.PREFERRED, 8.0, CellsLayout.FILL, },
          {CellsLayout.FILL, }
     };

     private CellsLayout tbKlaeren_panel1_layout = new CellsLayout(tbKlaeren_panel1_constraints, 8, 8);

     private double[][] tbKlaeren_panel1_panel2_constraints = {
          {20.0, },
          {158.0, 20.0, 90.0, 60.0, 60.0, 20.0, 20.0, }
     };

     private CellsLayout tbKlaeren_panel1_panel2_layout = new CellsLayout(tbKlaeren_panel1_panel2_constraints, 8, 8);

     private double[][] tbKlaeren_panel3_constraints = {
          {20.0, 20.0, 20.0, CellsLayout.FILL, 10.0, 20.0, 10.0, 20.0, 20.0, 20.0, 20.0, 10.0, },
          {133.0, 90.0, 20.0, 20.0, 20.0, 20.0, 149.0, 129.0, 20.0, 20.0, CellsLayout.FILL, }
     };

     private CellsLayout tbKlaeren_panel3_layout = new CellsLayout(tbKlaeren_panel3_constraints, 8, 8);

     private double[][] tbKlaeren_panel3_panel4_constraints = {
          {20.0, 20.0, 20.0, 20.0, 20.0, CellsLayout.FILL, },
          {CellsLayout.FILL, 129.0, }
     };

     private CellsLayout tbKlaeren_panel3_panel4_layout = new CellsLayout(tbKlaeren_panel3_panel4_constraints, 4, 4);

     private double[][] panel5_constraints = {
          {20.0, },
          {CellsLayout.FILL, CellsLayout.PREFERRED, CellsLayout.PREFERRED, CellsLayout.PREFERRED, }
     };

     private CellsLayout panel5_layout = new CellsLayout(panel5_constraints, 4, 4);

     private JLabel lbZablstapel = new JLabel();
     private JTextField txZahlstapel = new JTextField();
     private JLabel lbPosition = new JLabel();
     private JTextField txPosition = new JTextField();
     private JLabel lbZahlungsdaten = new JLabel();
     private JLabel lbKonto = new JLabel();
     private JTextField txKonto = new JTextField();
     private JLabel lbBlz = new JLabel();
     private JTextField txBlz = new JTextField();
     private JLabel lbAufgb = new JLabel();
     private JTextField tcAufgb = new JTextField();
     private JLabel lbVerw = new JLabel();
     private JTextField txVerw = new JTextField();
     private JLabel lbEzv = new JLabel();
     private JTextField textfield7 = new JTextField();
     private JLabel lbMeldMash = new JLabel();
     private JScrollPane scVerMash = new JScrollPane();
     private JTextArea taVerMash = new JTextArea();
     private JLabel lbMeldMan = new JLabel();
     private JScrollPane scMeldMan = new JScrollPane();
     private JTextArea taMeldMan = new JTextArea();
     private JLabel lbZahlbetrag = new JLabel();
     private JTextField txZahlbetrag = new JTextField();
     private JLabel lbRest = new JLabel();
     private JTextField txRest = new JTextField();
     private JCheckBox chAkonto = new JCheckBox();
     private JLabel lbHerkunft = new JLabel();
     private JComboBox coHerkunft = new JComboBox();
     private JLabel lbKlaeren = new JLabel();
     private JTabbedPane tbKlaeren = new JTabbedPane();
     JPanel tbKlaeren_panel1 = new JPanel();
     JScrollPane tbKlaeren_panel1_scrollpane3 = new JScrollPane();
     JTable tbKlaeren_panel1_scrollpane3_table1 = new JTable();
     JPanel tbKlaeren_panel1_panel2 = new JPanel();
     JButton tbKlaeren_panel1_panel2_button1 = new JButton();
     JLabel tbKlaeren_panel1_panel2_label15 = new JLabel();
     JTextField tbKlaeren_panel1_panel2_textfield10 = new JTextField();
     JButton tbKlaeren_panel1_panel2_button2 = new JButton();
     JButton tbKlaeren_panel1_panel2_button3 = new JButton();
     JPanel tbKlaeren_panel3 = new JPanel();
     JScrollPane tbKlaeren_panel3_scrollpane4 = new JScrollPane();
     JTable tbKlaeren_panel3_scrollpane4_table2 = new JTable();
     JLabel tbKlaeren_panel3_label16 = new JLabel();
     JTextField tbKlaeren_panel3_textfield11 = new JTextField();
     JPanel tbKlaeren_panel3_panel4 = new JPanel();
     JButton tbKlaeren_panel3_panel4_button4 = new JButton();
     JButton tbKlaeren_panel3_panel4_button5 = new JButton();
     JButton tbKlaeren_panel3_panel4_button6 = new JButton();
     JButton tbKlaeren_panel3_panel4_button7 = new JButton();
     JButton tbKlaeren_panel3_panel4_button8 = new JButton();
     JLabel tbKlaeren_panel3_label17 = new JLabel();
     JLabel tbKlaeren_panel3_label18 = new JLabel();
     JTextField tbKlaeren_panel3_textfield12 = new JTextField();
     JButton tbKlaeren_panel3_button9 = new JButton();
     JButton tbKlaeren_panel3_button10 = new JButton();
     JLabel tbKlaeren_panel3_label19 = new JLabel();
     JTextField tbKlaeren_panel3_textfield13 = new JTextField();
     JButton tbKlaeren_panel3_button11 = new JButton();
     JButton tbKlaeren_panel3_button12 = new JButton();
     JLabel tbKlaeren_panel3_label20 = new JLabel();
     JTextField tbKlaeren_panel3_textfield14 = new JTextField();
     JLabel tbKlaeren_panel3_label21 = new JLabel();
     JTextField tbKlaeren_panel3_textfield15 = new JTextField();
     JButton tbKlaeren_panel3_button13 = new JButton();
     JButton tbKlaeren_panel3_button14 = new JButton();
     JLabel tbKlaeren_panel3_label22 = new JLabel();
     JTextField tbKlaeren_panel3_textfield16 = new JTextField();
     JPanel panel5 = new JPanel();
     JButton panel5_button15 = new JButton();
     private JButton btAusgleichen = new JButton();
     private JButton btAbbrechen = new JButton();

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     public WebSwing() {
          doInit();
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void doInit() {
          setLayout(layout);

          lbZablstapel.setName("lbZablstapel");
          lbZablstapel.setText("Zahlstapel:");
          txZahlstapel.setEditable(Boolean.FALSE);
          txZahlstapel.setName("txZahlstapel");
          txZahlstapel.setText("");
          lbPosition.setName("lbPosition");
          lbPosition.setText("Position:");
          txPosition.setEditable(Boolean.FALSE);
          txPosition.setName("txPosition");
          txPosition.setText("");
          lbZahlungsdaten.setFont(new Font("Tahoma Fett", 1, 11));
          lbZahlungsdaten.setName("lbZahlungsdaten");
          lbZahlungsdaten.setText("Zahlungsdaten");
          lbKonto.setName("lbKonto");
          lbKonto.setText("Kontonummer:");
          txKonto.setEditable(Boolean.FALSE);
          txKonto.setName("txKonto");
          txKonto.setText("");
          lbBlz.setName("lbBlz");
          lbBlz.setText("Bankleitzahl:");
          txBlz.setEditable(Boolean.FALSE);
          txBlz.setName("txBlz");
          txBlz.setText("");
          lbAufgb.setName("lbAufgb");
          lbAufgb.setText("Auftraggeber:");
          tcAufgb.setEditable(Boolean.FALSE);
          tcAufgb.setName("tcAufgb");
          tcAufgb.setText("");
          lbVerw.setName("lbVerw");
          lbVerw.setText("Verwendungszweck:");
          txVerw.setEditable(Boolean.FALSE);
          txVerw.setName("txVerw");
          txVerw.setText("");
          lbEzv.setName("lbEzv");
          lbEzv.setText("EZV-Refererenz-Nr:");
          textfield7.setEditable(Boolean.FALSE);
          textfield7.setText("");
          lbMeldMash.setName("lbMeldMash");
          lbMeldMash.setText("Verarbeitungsmeldungen masch.:");
          scVerMash.getViewport().add(taVerMash);
          taVerMash.setText("");
          lbMeldMan.setName("lbMeldMan");
          lbMeldMan.setText("Verarbeitungsmeldungen man.:");
          scMeldMan.getViewport().add(taMeldMan);
          taMeldMan.setText("");
          lbZahlbetrag.setName("lbZahlbetrag");
          lbZahlbetrag.setText("Zahlbetrag:");
          txZahlbetrag.setName("txZahlbetrag");
          txZahlbetrag.setText("700,00 EUR");
          lbRest.setName("lbRest");
          lbRest.setText("Restbetrag:");
          txRest.setEditable(Boolean.FALSE);
          txRest.setName("txRest");
          txRest.setText("");
          chAkonto.setName("chAkonto");
          chAkonto.setText("Akonto");
          lbHerkunft.setName("lbHerkunft");
          lbHerkunft.setText("Herkunft:");
          coHerkunft.setName("coHerkunft");
          lbKlaeren.setFont(new Font("Tahoma Fett", 1, 11));
          lbKlaeren.setName("lbKlaeren");
          lbKlaeren.setText("Klären");
          tbKlaeren.setName("tbKlaeren");
          tbKlaeren_panel1_scrollpane3.getViewport().add(tbKlaeren_panel1_scrollpane3_table1);
          tbKlaeren_panel1_scrollpane3_table1.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4", 
               }
          ));
          tbKlaeren_panel1_panel2_button1.setText("weiteres TK-Konto klären");
          tbKlaeren_panel1_panel2_label15.setText("Versicherten-Nr.:");
          tbKlaeren_panel1_panel2_textfield10.setText("");
          tbKlaeren_panel1_panel2_button2.setText("...");
          tbKlaeren_panel1_panel2_button3.setText("...");
          tbKlaeren_panel3_scrollpane4.getViewport().add(tbKlaeren_panel3_scrollpane4_table2);
          tbKlaeren_panel3_scrollpane4_table2.setModel(new DefaultTableModel( 
               new Object [][] {
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    {null, null, null, null, },
                    
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4", 
               }
          ));
          tbKlaeren_panel3_label16.setText("(Teil-)Betrag:");
          tbKlaeren_panel3_textfield11.setText("");
          tbKlaeren_panel3_panel4_button4.setText("Neue Einzelzeile");
          tbKlaeren_panel3_panel4_button5.setText("Lösche Zeile");
          tbKlaeren_panel3_panel4_button6.setText("Verwerfen");
          tbKlaeren_panel3_panel4_button7.setText("Akzeptieren");
          tbKlaeren_panel3_panel4_button8.setText("Akzeptieren & Neu");
          tbKlaeren_panel3_label17.setText("Arbeitgeberbeitrag");
          tbKlaeren_panel3_label18.setText("Versicherungsobjekt");
          tbKlaeren_panel3_textfield12.setText("");
          tbKlaeren_panel3_button9.setText("...");
          tbKlaeren_panel3_button10.setText("...");
          tbKlaeren_panel3_label19.setText("Abrechnungssatz:");
          tbKlaeren_panel3_textfield13.setText("");
          tbKlaeren_panel3_button11.setText("...");
          tbKlaeren_panel3_button12.setText("...");
          tbKlaeren_panel3_label20.setText("Beitragsmonat:");
          tbKlaeren_panel3_textfield14.setText("");
          tbKlaeren_panel3_label21.setText("Geschäftspartnerposition");
          tbKlaeren_panel3_textfield15.setText("");
          tbKlaeren_panel3_button13.setText("...");
          tbKlaeren_panel3_button14.setText("...");
          tbKlaeren_panel3_label22.setText("Rückzahlung Insolvenzgeld:");
          tbKlaeren_panel3_textfield16.setText("");
          panel5_button15.setText("Fertigstellen");
          btAusgleichen.setName("btAusgleichen");
          btAusgleichen.setText("Ausgleichen");
          btAbbrechen.setName("btAbbrechen");
          btAbbrechen.setText("Abbrechen");

          initPanel5();
          initTbKlaeren_panel1();
          initTbKlaeren_panel1_panel2();
          initTbKlaeren_panel3();
          initTbKlaeren_panel3_panel4();

          add(lbZablstapel, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txZahlstapel, new CellsLayout.Cell(0, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbPosition, new CellsLayout.Cell(0, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txPosition, new CellsLayout.Cell(0, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbZahlungsdaten, new CellsLayout.Cell(1, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbKonto, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txKonto, new CellsLayout.Cell(2, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbBlz, new CellsLayout.Cell(2, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txBlz, new CellsLayout.Cell(2, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbAufgb, new CellsLayout.Cell(2, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tcAufgb, new CellsLayout.Cell(2, 7, false, 0, 2, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbVerw, new CellsLayout.Cell(3, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txVerw, new CellsLayout.Cell(3, 1, false, 0, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbEzv, new CellsLayout.Cell(4, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(textfield7, new CellsLayout.Cell(4, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbMeldMash, new CellsLayout.Cell(5, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scVerMash, new CellsLayout.Cell(5, 1, false, 2, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbMeldMan, new CellsLayout.Cell(8, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(scMeldMan, new CellsLayout.Cell(8, 1, false, 2, 8, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbZahlbetrag, new CellsLayout.Cell(11, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txZahlbetrag, new CellsLayout.Cell(11, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbRest, new CellsLayout.Cell(11, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(txRest, new CellsLayout.Cell(11, 4, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(chAkonto, new CellsLayout.Cell(11, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbHerkunft, new CellsLayout.Cell(11, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(coHerkunft, new CellsLayout.Cell(11, 8, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          add(lbKlaeren, new CellsLayout.Cell(13, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          add(tbKlaeren, new CellsLayout.Cell(14, 0, false, 0, 9, CellsLayout.LEFT, CellsLayout.TOP));
          add(panel5, new CellsLayout.Cell(15, 4, false, 0, 5, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initPanel5() {
          panel5.setLayout(panel5_layout);
          panel5.add(panel5_button15, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel5.add(btAusgleichen, new CellsLayout.Cell(0, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          panel5.add(btAbbrechen, new CellsLayout.Cell(0, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTbKlaeren_panel1() {
          tbKlaeren_panel1.setLayout(tbKlaeren_panel1_layout);
          tbKlaeren_panel1.add(tbKlaeren_panel1_scrollpane3, new CellsLayout.Cell(2, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel1.add(tbKlaeren_panel1_panel2, new CellsLayout.Cell(0, 0, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren.add("Auf TK-Konto", tbKlaeren_panel1);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTbKlaeren_panel1_panel2() {
          tbKlaeren_panel1_panel2.setLayout(tbKlaeren_panel1_panel2_layout);
          tbKlaeren_panel1_panel2.add(tbKlaeren_panel1_panel2_button1, new CellsLayout.Cell(0, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel1_panel2.add(tbKlaeren_panel1_panel2_label15, new CellsLayout.Cell(0, 2, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel1_panel2.add(tbKlaeren_panel1_panel2_textfield10, new CellsLayout.Cell(0, 3, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel1_panel2.add(tbKlaeren_panel1_panel2_button2, new CellsLayout.Cell(0, 5, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel1_panel2.add(tbKlaeren_panel1_panel2_button3, new CellsLayout.Cell(0, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTbKlaeren_panel3() {
          tbKlaeren_panel3.setLayout(tbKlaeren_panel3_layout);
          tbKlaeren_panel3.add(tbKlaeren_panel3_scrollpane4, new CellsLayout.Cell(0, 0, false, 3, 10, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label16, new CellsLayout.Cell(5, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield11, new CellsLayout.Cell(5, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_panel4, new CellsLayout.Cell(5, 10, false, 5, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label17, new CellsLayout.Cell(7, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label18, new CellsLayout.Cell(7, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield12, new CellsLayout.Cell(7, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button9, new CellsLayout.Cell(7, 8, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button10, new CellsLayout.Cell(7, 9, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label19, new CellsLayout.Cell(8, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield13, new CellsLayout.Cell(8, 1, false, 0, 1, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button11, new CellsLayout.Cell(8, 3, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button12, new CellsLayout.Cell(8, 4, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label20, new CellsLayout.Cell(9, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield14, new CellsLayout.Cell(9, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label21, new CellsLayout.Cell(9, 6, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield15, new CellsLayout.Cell(9, 7, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button13, new CellsLayout.Cell(9, 8, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_button14, new CellsLayout.Cell(9, 9, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_label22, new CellsLayout.Cell(10, 0, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3.add(tbKlaeren_panel3_textfield16, new CellsLayout.Cell(10, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren.add("Auf Vertragskonto  Geschäftspartnerkonto", tbKlaeren_panel3);
     }

    /**
     * @param
     *
     * @return
     *
     * @exception
     *
     * @see
     */
     private void initTbKlaeren_panel3_panel4() {
          tbKlaeren_panel3_panel4.setLayout(tbKlaeren_panel3_panel4_layout);
          tbKlaeren_panel3_panel4.add(tbKlaeren_panel3_panel4_button4, new CellsLayout.Cell(0, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3_panel4.add(tbKlaeren_panel3_panel4_button5, new CellsLayout.Cell(1, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3_panel4.add(tbKlaeren_panel3_panel4_button6, new CellsLayout.Cell(2, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3_panel4.add(tbKlaeren_panel3_panel4_button7, new CellsLayout.Cell(3, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
          tbKlaeren_panel3_panel4.add(tbKlaeren_panel3_panel4_button8, new CellsLayout.Cell(4, 1, false, 0, 0, CellsLayout.LEFT, CellsLayout.TOP));
     }

}

